### PR TITLE
Dnadales/861 docker linux package builder

### LINKED ISSUE #821: Torxakis v0.7 not working for Ubuntu 16.04
After installing Torxakis 0.7 using the .deb file in Ubuntu 16.04, an error message is given when using the tool (see attachment).

My colleague, who is trying to use it did some research and it seems not to be a good idea to update GLIB. The solution for him was to use Ubuntu 18.04. However, I do have 0.7 in my Ubuntu 16.04, which I built from source, maybe there is something wrong with the .deb file?

Regards.

screenshot from 2018-11-29 13-09-46
screenshot from 2018-11-29 13-13-54

### LINKED ISSUE #861: Create Linux installer for TorXakis 0.8.0

### PR DESCRIPTION
**Pull request by dnadales**
See mk-package/README.md

Closes #861 
Closes #821

### CODE REVIEW

File: ci/mk-package/ubuntu/mk-package.sh [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+
+TXS_BIN=`stack path --local-install-root --silent --stack-yaml stack_linux.yaml`/bin
+
+cp ${TXS_BIN}/* ${TXS_TMP}/usr/bin/
+
+export CACHE_DIR="/build"
+
+echo "Looking for cvc4 in ${CACHE_DIR}/usr/bin/)"
+
+if [ -f $CACHE_DIR/usr/bin/cvc4 ] && [ -e $CACHE_DIR/usr/bin/cvc4-1.7 ]
```
Comment (pjljvandelaar) [inline ci/mk-package/ubuntu/mk-package.sh:47]: So this file must be updated when we update cvc4 and/or z3.
Added comment to https://github.com/TorXakis/TorXakis/issues/897 to remind us.
Maybe somewhere in the future we should localize this in a single place...

**Review by pjljvandelaar — APPROVED** [review]
little to no experience with docker, so I rely on you!

**Comment by pjljvandelaar** [comment]
We have an issue with the copyright  requirement:
```
Searching for Copyright notice:
TorXakis - Model Based Testing
Copyright (c) 2015-2017 TNO and Radboud University
See LICENSE at root directory of this repository.

./ci/mk-package/ubuntu/mk-package.sh
#Files = 419
#Violations = 1
Fail
Use /test/copyright/FixCopyrightNotices.bat to add missing copyright notices.
```
How to solve it?
Especially,  since both `#!/bin/bash` and our copyright want to be at the first line.

**Comment by pjljvandelaar** [comment]
It seems I can't reopen this pull request, so I am making a new issue out of it.

File: ci/mk-package/ubuntu/mk-package.sh (hunk 1 above)
Comment (dnadales) [reply ci/mk-package/ubuntu/mk-package.sh:47]: Yeah, but the right thing to do would be to have bash functions for downloading `cvc4` and `z3` to given locations, and use them in `ci` and `ci/mk-package`. I didn't do it here, since I ran out of time, and it'd require additional testing (that I didn't break CI).

**Comment by dnadales** [comment]
Oh, darn, I forgot to add the copyright notice there (how come it passed CI?).

The other shell files begin like this:

```sh
#!/bin/bash

# TorXakis - Model Based Testing
# Copyright (c) 2015-2017 TNO and Radboud University
# See LICENSE at root directory of this repository.

```

I think this should keep the copyright tyrant happy :)

**Comment by pjljvandelaar** [comment]
Indeed: how did it pass CI? See #902
