### PR TITLE
Configure parameters from config file

### LINKED ISSUE #561: Moving Arms #model Restricted Axis Purpose Test (input eagerness 0) fails in nightly builds
Some of the cases are because SUT simulator is still too late to answer, so 5500ms Sut_deltaTime is not enough.

Other cases are because Tester starts way earlier than SUT simulator then times out before the simulator can show up and accept connection.

### PR DESCRIPTION
**Pull request by keremispirli**
Removes `defs/Params.hs` which is already defined in other files
Adds support for reading parameters from the configuration file (`.torxakis.yaml`)

Fixes #561 along the way

### CODE REVIEW

File: sys/core/src/TxsCore.hs [hunk 1]
```diff
@@ -104,6 +104,7 @@ module TxsCore
 
   -- * LPE transformation
 , txsLPE
+, updateParams
```
Comment (capitanbatata) [inline sys/core/src/TxsCore.hs]: From the comments it seems that `updateParams` is related to the LPE transformation. Shouldn't this function be under the `Parameters` section above?

File: sys/core/src/TxsCore.hs [hunk 2]
```diff
@@ -172,16 +173,25 @@ import VarId
...
+                        , IOC.unid   = 0
+                        , IOC.params = updateParams initParams
+                                        $ Config.configuredParameters initConfig
+                        , IOC.state  = initState
+                        }
+      return ()
+      where initState = IOC.Noning
+            initParams =
+              Map.union ParamCore.initParams SolveDefs.Params.initParams
+
```
Comment (capitanbatata) [inline sys/core/src/TxsCore.hs]: We need some documentation on what the `updateParams` function does.

Comment (capitanbatata) [reply sys/core/src/TxsCore.hs]: You can even put the types in multiple lines (making the line shorter than 80 characters):

```haskell
-- | This function does ...
updateParams :: ParamCore.Params -- ^ Foo ...
             -> [(Config.ParameterName,Config.ParameterValue)] -- ^ Bar ...
             -> ParamCore.Params
```

File: sys/coreenv/src/Config.hs [hunk 3]
```diff
@@ -33,16 +36,22 @@ data SolverConfig = SolverConfig
 newtype SolverId = SolverId { solverId :: String }
   deriving (Eq, Ord, Show)
 
+newtype ParameterName = ParamName { getParamName :: String }
```
Comment (capitanbatata) [inline sys/coreenv/src/Config.hs]: We should be consistent with the naming: either `ParameterName` or `ParamName` (to me the shorter the better :)).

Also we could get rid of the `get` part, since we don't use this prefix in all the other accesor functions (`solverId`, `smtLog`, etc).

File: sys/core/src/TxsCore.hs [hunk 4]
```diff
@@ -172,16 +173,25 @@ import VarId
...
+updateParams :: ParamCore.Params -> [(Config.ParameterName,Config.ParameterValue)] -> ParamCore.Params
+updateParams = foldl applyConfParam
+  where applyConfParam allParams (Config.ParamName pnStr, Config.ParamValue pvStr) =
```
Comment (capitanbatata) [inline sys/core/src/TxsCore.hs]: Putting the type of the helper function might help understanding what's going on here:

```haskell
    applyConfParam :: ParamCore.Params -> (Config.ParameterName, Config.ParameterValue) -> ParamCore.Params
```

File: sys/core/src/TxsCore.hs (hunk 2 above)
Comment (capitanbatata) [reply sys/core/src/TxsCore.hs]: Oh, and I miss a space after the comma :D

File: sys/core/src/TxsCore.hs [hunk 5]
```diff
@@ -172,16 +173,25 @@ import VarId
...
+          Map.adjust (updateOldParamWith pvStr) ("param_" ++ pnStr) allParams
```
Comment (capitanbatata) [inline sys/core/src/TxsCore.hs]: Something that might be a source of headaches in the future is that the knowledge that we have to prepend `"param_" to the parameter name is hidden here. Isn't the `Config` module a better place for it? You could make the accessor function private, and export a `getTxsParamName` (or something like that) which will perform this transformation. In that way we might prevent errors in the future.

File: sys/coreenv/src/Config.hs [hunk 6]
```diff
@@ -33,16 +36,22 @@ data SolverConfig = SolverConfig
...
 -- | TorXakis configuration options.
 data Config = Config
   { -- | Log all SMT commands?
     smtLog           :: Bool
     -- | Available solvers that can be chosen from.
-  , availableSolvers :: Map.Map SolverId SolverConfig
-  , selectedSolver   :: SolverId
+  , availableSolvers     :: Map.Map SolverId SolverConfig
+  , selectedSolver       :: SolverId
+  , configuredParameters :: [(ParameterName,ParameterValue)]
```
Comment (capitanbatata) [inline sys/coreenv/src/Config.hs]: We need some documentation on what `configuredParameters` are (and also we need to update the readme/user-manual-which-doesn't-exists-yet so that people are aware of this possibility).

File: sys/defs/src/Params.hs [hunk 7]
```diff
@@ -1,106 +0,0 @@
-{-
```
Comment (capitanbatata) [inline sys/defs/src/Params.hs]: We got rid of 100 LOC? Nice. 

> "Perfection is Achieved Not When There Is Nothing More to Add, But When There Is Nothing Left to Take Away"

;)

File: sys/server/src/TxsServer.hs [hunk 8]
```diff
@@ -81,21 +81,22 @@ main = withSocketsDo $ do
...
+      (portNr, sock) <- txsListenOn $ (clPortNumber . SC.cmdLineCfg) uConfig
+      (hs, host, _) <- accept sock
+      hSetBuffering hs LineBuffering
+      hSetEncoding hs latin1
+      hPutStrLn stderr "\nTXSSERVER >>  Starting  ..... \n"
+      let initS = IOS.envsNone
+              { IOS.host   = host
+              , IOS.portNr = portNr
+              , IOS.servhs = hs
+              , IOS.params = TxsCore.updateParams (IOS.params IOS.envsNone) $ SC.configuredParameters config
```
Comment (capitanbatata) [inline sys/server/src/TxsServer.hs]: To me it looks strange that we have to call the `updateParams` function twice. We're calling `runTxsCore` below, which will do this again. I know you @keremispirli explained me why, but maybe it a good idea to:

    - include a comment on why this is done.
    - if there's no good reason for updating the parameters twice submit an issue to fix this.

File: sys/core/src/TxsCore.hs [hunk 9]
```diff
@@ -172,16 +173,25 @@ import VarId
...
+                        , IOC.params = updateParams initParams
+                                        $ Config.configuredParameters initConfig
+                        , IOC.state  = initState
+                        }
+      return ()
+      where initState = IOC.Noning
+            initParams =
+              Map.union ParamCore.initParams SolveDefs.Params.initParams
+
+updateParams :: ParamCore.Params -> [(Config.ParameterName,Config.ParameterValue)] -> ParamCore.Params
```
Comment (capitanbatata) [inline sys/core/src/TxsCore.hs]: Shouldn't this function be part of `Config` or `Params`?

File: sys/core/src/TxsCore.hs (hunk 1 above)
Comment (keremispirli) [reply sys/core/src/TxsCore.hs]: Fixed

File: sys/core/src/TxsCore.hs (hunk 2 above)
Comment (keremispirli) [reply sys/core/src/TxsCore.hs]: Fixed and moved to Config

File: sys/coreenv/src/Config.hs (hunk 3 above)
Comment (keremispirli) [reply sys/coreenv/src/Config.hs]: Fixed

File: sys/core/src/TxsCore.hs (hunk 4 above)
Comment (keremispirli) [reply sys/core/src/TxsCore.hs]: Added

File: sys/core/src/TxsCore.hs (hunk 5 above)
Comment (keremispirli) [reply sys/core/src/TxsCore.hs]: Moved to Config, looks like it's not needed anymore since this is now internal in Config

File: sys/defs/src/Params.hs (hunk 7 above)
Comment (keremispirli) [reply sys/defs/src/Params.hs]: 🎉

File: sys/coreenv/src/Config.hs (hunk 6 above)
Comment (keremispirli) [reply sys/coreenv/src/Config.hs]: I thought the name was self-explaining...

File: sys/server/src/TxsServer.hs (hunk 8 above)
Comment (keremispirli) [reply sys/server/src/TxsServer.hs]: Added comments.
Parameters come from 3 different places, 2 are merged in TxsCore and the other is initial state in TxsServer, which later merges to others in `runStateT`. We can discuss the reason for keeping them separated with Pierre.

File: sys/core/src/TxsCore.hs (hunk 9 above)
Comment (keremispirli) [reply sys/core/src/TxsCore.hs]: Moved to Config

**Comment by pjljvandelaar** [comment]
Build failed twice:
On semaphoreci with
```
 src/Sqatt.hs:473: 
  1) Examples.All, Moving Arms, Restricted Axis Purpose Test (input eagerness 0)
       expected: Right ()
        but got: Left (TestExpectationError "Did not get expected result Pass")
```
On appveyor with
```
  src\Sqatt.hs:473: 
  1) Examples.All, Moving Arms, Restricted Axis Purpose Test (input eagerness 0)
       expected: Right ()
        but got: Left (TestExpectationError "Did not get expected result Pass")
```
It seems reproducible so the change seems to be the fault ;-(
Did you change the parameter values?
Any other idea?

File: test/sqatt/src/Sqatt.hs [hunk 10]
```diff
@@ -531,3 +540,15 @@ mkLogDir strPrefix = do
         currDateStr = toFSSafeStr (show currDate)
     mktree logDir
     return logDir
+
+emptyExample :: TxsExample
+emptyExample = TxsExample
```
Comment (pjljvandelaar) [inline test/sqatt/src/Sqatt.hs]: Why is emptyExample needed?
It doesn't seem to be related to parameters, but to setup and teardown actions.

Comment (keremispirli) [reply test/sqatt/src/Sqatt.hs]: Ah, that is something I forgot... I added setup and teardown actions because I have figured they're needed for testing this change. But I didn't add unit tests yet; that was the reason I have estimated 3 days. OK, more to be done here...

**Comment by keremispirli** [comment]
I'm still working on this branch to add tests; please don't delete it.
