### PR TITLE
Fixed showing logs for failed tests

### LINKED ISSUE #338: Logs are not shown for failed tests
After #238 all the logs for failed tests should be dumped to console, but they are not.

See:
https://semaphoreci.com/capitanbatata/torxakis/branches/develop/builds/82 (Also see how two tests both timed out but show different error messages)
https://semaphoreci.com/capitanbatata/torxakis/branches/develop/builds/77

Edit: Old links were dead.

### PR DESCRIPTION
**Pull request by keremispirli**
Fixes #338

### CODE REVIEW

File: test/sqatt/src/Sqatt.hs [hunk 1]
```diff
@@ -301,11 +302,11 @@ runTxsWithExample mLogDir ex = Concurrently $ do
       putStr "."
     timer = Concurrently $ do
       sleep sqattTimeout
-      throwIO TestTimedOut
+      return $ Left TestTimedOut
     txsUIProc mUiLogDir imf port =
-      Concurrently $ try $ do
+      Concurrently $ do
```
Comment (capitanbatata) [inline test/sqatt/src/Sqatt.hs]: Why was the `try` removed? We still need to catch errors in case the `txsUIShell` aborts with an error (for instance if a port number was busy).

Comment (keremispirli) [reply test/sqatt/src/Sqatt.hs]: It's back 👍
