### PR TITLE
Pass the right parameters to `translate`.

### LINKED ISSUE #802: Alternative StAutDef not working
I changed the Fibonacci example to use the alternative StAutDef definition:
```
CHANDEF Channels ::=
    Input, Output :: Int
ENDDEF

STAUTDEF fibonacci [Input, Output :: Int]() ::=
    VAR   fibm, fibn, count, max :: Int
    STATE inputState, outputState
    INIT  inputState
    TRANS inputState  -> Input  ? n    [[ (n > 0) /\ (n < 100) ]] { fibm := 0; fibn := 1; count := 1; max := n }   -> outputState
          outputState -> Output ! fibn [[ count == max ]]                                                          -> inputState
          outputState -> Output ! fibn [[ count < max ]] { fibm := fibn; fibn := fibm + fibn; count := count + 1 } -> outputState
ENDDEF 

MODELDEF Model ::=
    CHAN IN   Input
    CHAN OUT  Output
    BEHAVIOUR stdi_fibonacci [Input, Output]()
ENDDEF 
```
Although the parser accepts it, when going to stepper  mode I get:
```
PS C:\temp> torxakis .\fibonacci.txs

TXS >>  TorXakis :: Model-Based Testing

TXS >>  txsserver starting: "PC-17716.tsn.tno.nl" : 51348
TXS >>  Solver "cvc4" initialized : cvc4 [1.6]
TXS >>  TxsCore initialized
TXS >>  input files parsed:
TXS >>  .\fibonacci.txs
TXS >> stepper Model
TXS >>  Expand: Undefined process name: std_fibonacci
TXS >>  Stepper started
```

### PR DESCRIPTION
**Pull request by dnadales**
Fixes #802.

### CODE REVIEW

File: sys/bexpr/src/StautDef.hs [hunk 1]
```diff
@@ -27,51 +27,65 @@ import           ProcDef
...
 combineParameters params stateId vars' = params ++ (stateId:vars')
 
 -- | combine arguments of stautdef instantiation, state identifier, and stautdef variables into single argument list
 -- must be consistent with @combineParameters@
-combineArguments :: [VExpr] -> VExpr -> [VExpr] -> [VExpr] 
+combineArguments :: [VExpr] -> VExpr -> [VExpr] -> [VExpr]
 combineArguments params stateId vars' = params ++ (stateId:vars')
 
-translate :: Map.Map FuncId (FuncDef VarId) -> Id -> Id -> Name -> [ChanId] -> [VarId] -> ExitSort -> [StatId] -> [VarId] -> [Trans] -> StatId -> VEnv -> (ProcDef, BExpr)
+translate
```
Comment (dnadales) [inline sys/bexpr/src/StautDef.hs:44]: @pjljvandelaar could you document the other parameters? (and maybe improve the documentation I added :) )

**Review by pjljvandelaar — APPROVED** [review]

File: sys/bexpr/src/StautDef.hs (hunk 1 above)
Comment (pjljvandelaar) [reply sys/bexpr/src/StautDef.hs:44]: Ok, Will pick it up in refactor/all branch.
