### PR TITLE
Fixed wobbly tests

### LINKED ISSUE #100: DisPro10-data, DisPro12-unique-id, MultipleControlLoops_SpecProduce examples fail
Observed in #97 

Failures of **Test build** and **Torxakis build** are about DatChecker; I fixed them in #99 . But failing **DisPro** and **MultipleControlLoops** tests are weird; they don't look like timing issues.

DAT Report:

Checking development acceptance test output for file 17Aug_153942.21_DatOutput.datr
- TestCopyright:         PASS
**- Test build:            FAIL** *(DatChecker should be updated)*
**- Torxakis build:        FAIL** *(DatChecker should be updated)*
- SelfTests:             PASS
- TestExamps:
--- StimulusResponse Tests
----- StimulusResponse Test 1: PASS
----- StimulusResponse Test 2: PASS
----- StimulusResponse Test 3: PASS
----- StimulusResponse Test 4: PASS
----- StimulusResponse Test 5: PASS
--- CustomersOrders Tests
----- CustomersOrders Test: PASS
--- LuckyPeople Tests
----- LuckyPeople Test 1: PASS
----- LuckyPeople Test 2: PASS
--- Adder Tests
----- Adder Test 1 - Basic: PASS
----- Adder Test 2 - State Automation: PASS
----- Adder Test 3 - Parallel Adders: PASS
--- DispatchProcess Tests
----- DisPro01-processor Test: PASS
----- DisPro02-dispatch Test: PASS
----- DisPro03-processors Test: PASS
----- DisPro04-hide Test: PASS
----- DisPro05-data Test: PASS
----- DisPro05a-data-nohide Test: PASS
----- DisPro06-datapos Test: PASS
----- DisPro06a-datapos-nohide Test: PASS
----- DisPro07-gcd Test: PASS
----- DisPro08-gcdpurp Test: PASS
----- DisPro09-multiproc Test: PASS
**----- DisPro10-data Test: FAIL**
**----- DisPro12-unique-id Test: FAIL**
----- DisPro12-unique-id_Wrong Test: PASS
----- DisPro12-unique-id_Right Test: PASS
--- ControlLoop Tests
----- ControlLoopModel Test: PASS
**----- MultipleControlLoops_SpecProduce Test: FAIL**
----- MultipleControlLoops_SpecMeasure Test: PASS
----- MultipleControlLoops_SpecCorrect Test: PASS
----- MultipleControlLoops_Spec Test: PASS
--- Echo Tests
----- Echo Stepper Test: PASS
----- Echo Simulator Test: PASS
--- Moving Arms Tests
----- MovingArms Stepper Test: PASS
----- MovingArms_Purpose Stepper Test: PASS
--- Point Tests
----- Point Stepper Test: PASS
----- Point_Purpose Stepper Test: PASS
--- Queue Tests
----- Queue Stepper Test: PASS
----- Queue_Lossy Stepper Test: PASS
----- Queue SUT Test: PASS
----- QueueStAut Stepper Test: PASS
----- QueueStAut_Lossy Stepper Test: PASS
--- ReadWriteConflict Tests
----- ReadWrite Stepper Test: PASS
----- ReadWrite7 Stepper Test: PASS
----- ReadWriteAdvanced Stepper Test: PASS
Checking finished

DatOutput
[17Aug_153942.21_DatOutput.datr.txt](https://github.com/TorXakis/TorXakis/files/1205140/17Aug_153942.21_DatOutput.datr.txt)

### LINKED ISSUE #227: Remove possibly failing tests from test set
Some tests fail.
E.g due to possible time out and due to using the same id, causing a non-unique hidden step.
These tests should be removed from the development acceptance test set.

### PR DESCRIPTION
**Pull request by keremispirli**
Please leave the merge to me, since build commands in Semaphore should also be updated.

Resolves #227 
Closes #100

### CODE REVIEW

File: ci/build.sh [hunk 1]
```diff
@@ -0,0 +1,2 @@
+# export PATH=$HOME/.local/bin:$CACHE_DIR/z3/bin:$CACHE_DIR/bin:$PATH
```
Comment (capitanbatata) [inline ci/build.sh]: Do we need this commented out line?

Comment (keremispirli) [reply ci/build.sh]: In theory not. I moved it to an external step in SemaphoreCI because *test.sh* and *test_long.sh* also need them, so I wanted to keep this line as a reminder in case we move again. Do you think it should go?

**Comment by keremispirli** [comment]
Only SpecProduce is disabled, didn't even remove it. Created #239 for it.

Adding documentation now.

File: ci/build.sh (hunk 1 above)
Comment (capitanbatata) [reply ci/build.sh]: I would say so. I'd rather have no commented out code. But it's a matter of personal taste.
